chat/chat/app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
    path('api/users/<int:pk>', views.user_list, name='user-detail'),
    path('api/users', views.user_list, name='user-list'),
    path('logout', LogoutView.as_view(next_page='index'), name='logout'),
    # path('<int:pk>', AboutView.as_view(), name='about'),
    path('<int:pk>', views.about_view, name='about'),
    path('register', views.register_view, name='register'),
    path('chat/create', views.roomcreate_view, name='room_create'),
    path('api/rooms/', views.room_list, name='roomlist'),
    path('chat/rooms/', views.rooms_view, name='room-list'),
    path('chat/rooms/<int:pk>', views.room, name='room_detail'),

    path('chat/rooms/subscribe/<int:pk>', views.subscribe_me),
    path('chat/rooms/unsubscribe/<int:pk>', views.unsubscribe_me),
]

chat/chat/chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from ckeditor_uploader import views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/chat/app/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = RichTextUploadingField(default='')

    def __str__(self):
        return self.user.username


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)


class Room(models.Model):
    room_name = models.TextField(verbose_name='Название комнаты')
    participants = models.ManyToManyField(User, blank=True, null=True)
    # messages = models.TextField(verbose_name='Сообщение')

    def get_absolute_url(self):
        return f'/{self.id}'


class Room_message(models.Model):
    send = models.ForeignKey(User, on_delete=models.CASCADE, related_name='send')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='room')
    text = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/chat/app/forms.py
from django.forms import ModelForm
from .models import UserProfile, Room
from django import forms
from django.forms.widgets import Textarea
from django.contrib.auth.models import Group
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class ProfileForm(ModelForm):
    avatar = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = UserProfile
        fields = ('user', 'avatar',)


class RoomForm(ModelForm):

    class Meta:
        model = Room
        fields = ('room_name', 'participants',)

chat/chat/templates/about.html
{% extends 'default.html' %}
<body>
{% block body %}
    {{ request.user}}
<!--    <form method="POST">-->
<!--        {% csrf_token %}-->
<!--        {{ form.media }}-->
<!--        {{ form.as_p }}-->
<!--        <input type="submit" value="Изменить">-->
<!--    </form>-->
<form id="update-form" method="post">
    {% csrf_token %}

    <div class="col s11">
        <div class="row">
            <div class="input-field">
                <input id="id_username" name="username" type="text" placeholder="Новое имя пользователя..">
                <label for="id_username" data-error="Это имя пользователя уже занято">Имя пользователя</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field">
                <label for="id_avatar">Аватар</label>
                <input id="id_avatar" name="avatar" type="file">
            </div>
        </div>
        <div class="col s1" style="line-height: 80px">
            <button style="background: #a8d8ff">Отправить</button>
        </div>
    </div>
</form>
<script>
    function update(username, avatar) {
        $.post('/api/users', '{"username": "' + username + '", "avatar": "' + avatar + '"}',
            function (data) {
                console.log(data);
                window.location = '/';
            }).fail(function (response) {
                $('#id_username').addClass('invalid');
            })
    }

    $(function () {
        $('#update-form').on('submit', function (event) {
            event.preventDefault();
            var username = $('#id_username').val();
            if(username !== '')
            {
                register(username, password);
            }
            else
                alert("Пожалуйста, введите корректное имя пользователя!");
        })
    })
    </script>
{% endblock body %}
</body>

chat/chat/templates/chat.html
{% extends 'default.html' %}
{% block body %}

    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
            <div class="card">
                <div id="users" class="collection">

                </div>
            </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Напишите свое сообщение..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button style="background: #a8d8ff">Отправить</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script>
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        $(function () {
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
            setInterval(() => {
                getUsers({{ request.user.id }}, doc => {
                    let list = ''
                    doc.map(userItem => {
                        list += userItem
                    })
                    $('#users').html(list)
                });
            }, 1000)
        })
    </script>
{% endblock %}

chat/chat/templates/default.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
        <nav class="blue lighten-3">
            <div class="nav-wrapper container">
              <a href="/" class="brand-logo">ЧатКом</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                  <li><a href="{% url 'room-list' %}">Комнаты</a></li>
                  <li>
                      {% if user.is_authenticated %}
                        <a href="{% url 'about' request.user.id %}">{{ request.user.username }}</a>
                      {% else %}
                        <a href="/">Профиль</a>
                      {% endif %}
                  </li>
                  <li>
                      {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                      {% else %}
                        <a class="nav-link" href="/">Войти</a>
                      {% endif %}
                  </li>
              </ul>
            </div>
        </nav>
    {% block body %}

    {% endblock %}
    </body>

  </html>

chat/chat/templates/index.html
{% extends 'default.html' %}
{% load static %}
    <body>
    {% block body %}
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Вход
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Имя пользователя</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Пароль</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Регистрация</a>
                            </div>
                            <div class="col s4">
                                <div class="right">
                                    <button class="btn blue waves-effect waves-light pull-s12">Войти</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

chat/chat/templates/messages.html
{% extends 'chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">Вы</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

chat/chat/templates/register.html
{% extends 'index.html' %}
{% block form %}
    <h3>
    Регистрация
    </h3>
    <form id="register-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input name="username" id="id_username" type="text" class="validate">
                <label for="id_username" data-error="Это имя пользователя уже занято">Имя пользователя</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="id_password" type="password">
                <label for="id_password">Пароль</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password2" id="id_password2" type="password">
                <label for="id_password2">Повторите пароль</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button class="btn blue waves-effect waves-light pull-s12">Зарегистрироваться</button>
            </div>
            </div>
        </div>
    </form>
    <script>
    function register(username, password) {
        $.post('/api/users', '{"username": "' + username + '", "password": "' + password + '"}',
            function (data) {
                console.log(data);
                window.location = '/';
            }).fail(function (response) {
                $('#id_username').addClass('invalid');
            })
    }

    $(function () {
        $('#register-form').on('submit', function (event) {
            event.preventDefault();
            var username = $('#id_username').val();
            if(username !== '')
            {
                var password = $('#id_password').val();
                if(password !== '' && password === $('#id_password2').val()){
                    register(username, password);
                }
                else{
                    alert("Пароли не совпадают!");
                }
            }
            else
                alert("Пожалуйста, введите корректное имя пользователя!");
        })
    })
    </script>
{% endblock %}

chat/chat/templates/room.html
{% extends 'default.html' %}

<body>
{% block body %}
<!--    <div class="card">-->
<!--            <div id="chat-log" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">-->
<!--&lt;!&ndash;                <textarea id="chat-log" cols="100" rows="20"></textarea><br>&ndash;&gt;-->
<!--            </div>-->
<!--    </div>-->
<!--    <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">-->
<!--        <div class="row">-->
<!--            <div class="col s11">-->
<!--                <div class="input-field">-->
<!--&lt;!&ndash;                    <input id="chat-message-input" name="message" type="text" placeholder="Напишите свое сообщение..">&ndash;&gt;-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col s1" style="line-height: 80px">-->
<!--&lt;!&ndash;                <input type="button" id="chat-message-submit" style="background: #a8d8ff">Отправить&ndash;&gt;-->
<!--            </div>-->
<!--        </div>-->
<!--    </form>-->
    <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
        {% block messages %}

        {% endblock %}
    </div>
    <div class="col s11">
        <div class="input-field">
            <input id="chat-message-input" type="text" size="100">
        </div>
    </div>
    <div class="col s1" style="line-height: 80px">
        <input id="chat-message-submit" type="button" style="background: #a8d8ff" value="Отправить">
    </div>
    {{ id_roomname|json_script:"id_roomname" }}
    <script>
        function isOpen(ws) { return ws.readyState === ws.OPEN }

        const roomName = JSON.parse(document.getElementById('id_roomname').textContent);
        let url = location.host == 'localhost' ?
          'ws://localhost:8080/ws' : location.host == 'javascript.local' ?
          'ws://javascript.local/article/websocket/chat/ws' :
          'wss://javascript.info/article/websocket/chat/ws';
        const chatSocket = new WebSocket(url);

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            if (!isOpen(chatSocket)) return;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
{% endblock body %}

chat/chat/templates/room_create.html
{% extends 'index.html' %}
{% block form %}
    <h3>
    Создание новой комнаты
    </h3>
    <form id="create-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input name="roomname" id="id_roomname" type="text" class="validate">
                <label for="id_roomname">Название комнаты</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Создать комнату</button>
                </div>
            </div>
        </div>
    </form>
    <script>
    function createRoom(roomname) {
        $.post('/api/rooms/', '{"room_name": "' + roomname + '"}',
            function (data) {
                console.log(data);
                window.location = '/';
            }).fail(function (response) {
                $('#id_roomname').addClass('invalid');
            })
    }

    $(function () {
        $('#create-form').on('submit', function (event) {
            event.preventDefault();
            var room_name = $('#id_roomname').val();
            if(room_name !== '')
            {
                createRoom(room_name);
            }
            else
                alert("Пожалуйста, введите корректное название!");
        })
    })
    </script>
{% endblock %}

chat/chat/templates/room_messages.html
{% extends 'room.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">Вы</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
{% endblock %}

chat/chat/templates/rooms.html
{% extends 'default.html' %}

<!--{% block title %}-->
<!--Rooms-->
<!--{% endblock title %}-->

{% block body %}

    <h3 style="text-align:center">
    Комнаты
    </h3>
    {% if rooms %}
        <table>
            <thead>
            <tr>
                <th style="text-align: center">
                    Комната
                </th>
                <th style="text-align: center">
                    Подписка
                </th>
            </tr>
            </thead>
            <tbody>
        {% for room in rooms %}
            <tr>
                <td style="text-align: center">
                    <a href="{% url 'room_detail' room.id %}">{{ room.room_name }}</a>
                </td>
                <td style="text-align: center">
                    {% if room in request.user.room_set.all %}
                        <a href="unsubscribe/{{ room.id }}">Отписаться</a>
                    {% else %}
                        <a href="subscribe/{{ room.id }}">Подписаться</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% else %}
        <h2>Комнат нет!</h2>
    {% endif %}
    <button class="btn blue waves-effect waves-light pull-s12" style="margin:auto;display:block;"><a href="{% url 'room_create' %}" style="color: white">Создать комнату</a></button>
{% endblock body %}